
# Boop boop

In [32]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import importlib

import utils
import models

In [2]:
train_articles = utils.load_articles('wikitext-103-raw/wiki.train.raw')
valid_articles = utils.load_articles('wikitext-103-raw/wiki.valid.raw')
test_articles = utils.load_articles('wikitext-103-raw/wiki.test.raw')

In [36]:
importlib.reload(utils)
char_encoding = utils.get_encoding(train_articles + valid_articles + test_articles)
char2int, int2char, int2hot, str2hot, hot2int, hot2str = char_encoding

In [30]:
hot2str(str2hot("This is a string with words"))

'This is a string with words'

In [66]:
importlib.reload(models)

rnn_net_50 = models.RNNModule(len(char2int), 50)
rnn_net_100 = models.RNNModule(len(char2int), 100)

lstm_net_50 = models.LSTMModule(len(char2int), 50)
lstm_net_100 = models.LSTMModule(len(char2int), 100)

In [67]:
#train rnn_net_50
models.train(rnn_net_50, train_articles, char_encoding)

tensor([[-8.3659, -8.3882, -8.5859,  ..., -8.7770, -8.5297, -8.7343],
        [-8.4545, -8.6247, -8.5470,  ..., -8.6887, -8.5007, -8.4336],
        [-8.4106, -8.4212, -8.5805,  ..., -8.7258, -8.5286, -8.5384],
        ...,
        [-8.3771, -8.5564, -8.6232,  ..., -8.5743, -8.7012, -8.5818],
        [-8.3444, -8.5152, -8.6012,  ..., -8.7393, -8.5903, -8.3186],
        [-8.3837, -8.5544, -8.6203,  ..., -8.5691, -8.6939, -8.5801]],
       grad_fn=<LogSoftmaxBackward>) tensor([943, 467, 943,  ..., 943, 467, 943])
tensor([[-8.2836, -8.2288, -8.6600,  ..., -8.5270, -8.2846, -8.6203],
        [-8.3657, -8.7497, -8.6082,  ..., -8.5486, -8.4919, -8.4992],
        [-8.4653, -8.4236, -8.4622,  ..., -8.7371, -8.6658, -8.4893],
        ...,
        [-8.3092, -8.5465, -8.5180,  ..., -8.5328, -8.7367, -8.5855],
        [-8.2882, -8.5193, -8.5259,  ..., -8.6900, -8.6037, -8.3429],
        [-8.3225, -8.5474, -8.5200,  ..., -8.5230, -8.7276, -8.5929]],
       grad_fn=<LogSoftmaxBackward>) tensor([ 943,

KeyboardInterrupt: 

In [7]:
#train rnn_net_100
models.train(rnn_net_100, train_articles, char_encoding)

In [68]:
#train lstm_net_50
models.train(lstm_net_50, train_articles, char_encoding)

tensor([[-8.6006, -8.6423, -8.5574,  ..., -8.8246, -8.4354, -8.8200],
        [-8.5514, -8.5638, -8.6003,  ..., -8.7144, -8.4416, -8.7473],
        [-8.5501, -8.5544, -8.5815,  ..., -8.6641, -8.4465, -8.7119],
        ...,
        [-8.5768, -8.5300, -8.4962,  ..., -8.5786, -8.4506, -8.6283],
        [-8.5741, -8.5126, -8.5064,  ..., -8.5873, -8.4521, -8.6359],
        [-8.5755, -8.5303, -8.4935,  ..., -8.5745, -8.4507, -8.6275]],
       grad_fn=<LogSoftmaxBackward>) tensor([943, 467, 943,  ..., 943, 467, 943])
tensor([[-8.3388, -8.6511, -8.6120,  ..., -8.3629, -8.5457, -8.5766],
        [-8.4492, -8.5891, -8.5365,  ..., -8.4939, -8.5252, -8.6435],
        [-8.5274, -8.5496, -8.5280,  ..., -8.5609, -8.5182, -8.6592],
        ...,
        [-8.5924, -8.5228, -8.4975,  ..., -8.6181, -8.4194, -8.6725],
        [-8.5891, -8.5068, -8.5072,  ..., -8.6263, -8.4209, -8.6803],
        [-8.5913, -8.5225, -8.4948,  ..., -8.6146, -8.4199, -8.6714]],
       grad_fn=<LogSoftmaxBackward>) tensor([ 943,

KeyboardInterrupt: 

In [9]:
#train lstm_net_100
models.train(lstm_net_100, train_articles, char_encoding)